# Minoc モデル設定例
# このファイルをmodels.tomlとしてコピーして使用してください

[gpt-4]
baseUrl = "https://api.openai.com/v1"
apiKey = "YOUR_OPENAI_API_KEY_HERE"
temperature = 0.7
top_p = 1.0
top_k = 50
max_tokens = 4096
customInstructions = """
あなたは親切で知識豊富なアシスタントです。
常に丁寧で正確な回答を心がけてください。
"""

[gpt-3.5-turbo]
baseUrl = "https://api.openai.com/v1"
apiKey = "YOUR_OPENAI_API_KEY_HERE"
temperature = 0.7
top_p = 1.0
top_k = 50
max_tokens = 4096

[claude-3-5-sonnet-20241022]
baseUrl = "https://api.anthropic.com/v1"
apiKey = "YOUR_ANTHROPIC_API_KEY_HERE"
temperature = 0.7
top_p = 1.0
top_k = 50
max_tokens = 4096
customInstructions = """
あなたは Claude 3.5 Sonnet です。
技術的な質問に対して詳細で実用的な回答を提供してください。
"""

[claude-3-haiku-20240307]
baseUrl = "https://api.anthropic.com/v1"
apiKey = "YOUR_ANTHROPIC_API_KEY_HERE"
temperature = 0.7
top_p = 1.0
top_k = 50
max_tokens = 4096 